spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/spending_management}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:hieu112004}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect